### ISSUE TITLE
switch from Visual mode to Normal mode responses too late

### ISSUE THREAD

**Issue by devindang** [kensleDev/vscode-nvim-ui#8]
The cursor changes its color even late for 5-10seconds as I switch nvim from Visual mode to Normal mode.

**Comment by kensleDev** [comment]
Unfortunately, it's a known issue. Please see here: [https://github.com/kensleDev/vscode-nvim-ui/issues/3](url) if you haven't already. Looking at the Issue now it does give the impression that it's completely fixed and that's my fault. 

The solution was to change the default advice to only apply color changes to the cursor color making it a lot less noticeable/jarring instead of the whole UI flashing.

I've made the jump and currently using Neovim full-time and don't have a lot of spare time to look at this right now. Happy to accept PR's if any Vim/VScode wizards can figure out what's going on here.

**Comment by martin-braun** [comment]
Link is dead. #3

**Comment by dav245** [comment]
Hey there! So i did a little digging and found this SO
https://vi.stackexchange.com/questions/38567/detecting-the-enter-and-leave-of-visual-mode-event

Grabbed out of it `autocmd Modechanged [vV\x16]*:*` and added following line to my init.lua file
`autocmd ModeChanged [vV\x16]*:* call VSCodeNotify('nvim-theme.normal')`

And it changes color back right after i exit visual mode. No more delays.

So possibly all that is needed is to update docs and all should work as expected.

**Comment by kensleDev** [comment]
Thanks @dav245, that's great news. I will update the docs once I've had time to test this tomorrow. Thanks again for your contribution!
